version: '3'
services:
  ku-tech:
    image: teerut26/ku-tech:latest
    environment:
      - DATABASE_URL=
      - NEXTAUTH_SECRET=
      - NEXTAUTH_URL=
      - CT_SECRET=
      - RECAPTCHA_SECRET=
      - EMAIL_USER=""
      - EMAIL_PASS=""
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - S3=
    ports:
      - 3000:3000
    # for docker swarm
    # deploy:
    #   replicas: 3