version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    resource_class: medium

    steps:
      - checkout

      - run:
          name: Check Docker daemon status
          command: docker version
      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/ku-tech:latest --build-arg NEXT_PUBLIC_CT_SITE_KEY=$NEXT_PUBLIC_CT_SITE_KEY --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY --build-arg NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID --build-arg NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL .

      # Push Docker image to registry
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/ku-tech:latest
      - run:
          name: "Trigger Portainer"
          command: curl --location --request POST $PT_TRIGGER_API

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
