version: 2.1

jobs:
  build:
    docker:
      - image: circleci/docker@1.7.0

    steps:
      - checkout

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/ku-tech:latest .

      # Push Docker image to registry
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/ku-tech:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
